service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  graphqlServerLambda:
    handler: apps/handler.graphqlServer
    events:
      - http:
          path: /graphql
          method: ANY