service: savvy-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: test
  region: us-east-1

plugins:
  - serverless-appsync-plugin

custom:
  appSync: # appsync plugin configuration
    name: ${self:service}-appsync-${self:provider.stage}
    authenticationType: API_KEY # since we don't have user login for now

functions:
  appSyncGraphqlResolvers:
    handler: app/graphql.handler

  getUsers:
    handler: app/getUsers.handler
    events:
      - http:
          path: /users
          method: GET