service: aws-serverless-offline
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  simpleLamdas:
    handler: LambdaFunctions/handler.hello
    events:
      - http:
          path: /hello
          method: get
  express:
    handler: express/index.handler
    events:
      - http: ANY /express/
      - http: 'ANY /express/{proxy+}'
  simpleGraphqlFunction:
    handler: graphql/getUserGraphql.handler
    events:
      - http:
          path: /graphql
          method: get