service: aws-serverless-offline
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  simpleLamdas:
    handler: LambdaFunctions/handler.hello
    events:
      - http:
          path: /hello
          method: get
  express:
    handler: express/index.handler
    events:
      - http: ANY /express/
      - http: 'ANY /express/{proxy+}'
  simpleGraphqlFunction:
    handler: graphql/getUserGraphql.handler
    events:
      - http:
          path: /graphql
          method: get
  dynamdbConnection:
    handler: lambdaDynamodb/getCategory.handler
    events:
      - http:
          path: /dynamodb/categories
          method: get
  graphqlInsert:
    handler:  graphql/getInputUserName.handler
    events:
      - http:
          path: /graph
          method: ANY

# resources:
#   Resources:
#     AuctionsTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: AuctionsTable
#         BillingMode: PAY_PER_REQUEST
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH